"""add ticker symbols and attribute history

Revision ID: 20a131a6a6a9
Revises: a65a0c67223e
Create Date: 2026-09-16 10:52:23.487431
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '20a131a6a6a9'
down_revision: Union[str, Sequence[str], None] = 'a65a0c67223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('ticker_symbol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'ticker_symbol')
    # ### end Alembic commands ###