"""add processing status

Revision ID: 4e6794a3ad27
Revises: 309711022336
Create Date: 2026-09-13 12:50:15.425209
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4e6794a3ad27'
down_revision: Union[str, Sequence[str], None] = '309711022336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the column with a database-level default.
    # Existing rows will automatically receive "pending".
    op.add_column(
        "documents",
        sa.Column(
            "processing_status",
            sa.String(),
            nullable=False,
            server_default="pending",
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###