"""add event lookup index

Revision ID: 627b588b631b
Revises: 62d11d64d9b7
Create Date: 2026-09-23 16:12:08.220277
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '627b588b631b'
down_revision: Union[str, Sequence[str], None] = '62d11d64d9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_entity_type_detected_at', 'events', ['primary_entity_id', 'event_type', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_entity_type_detected_at', table_name='events')
    # ### end Alembic commands ###