"""add event interpretations

Revision ID: 9ff29dda01d9
Revises: 627b588b631b
Create Date: 2026-09-23 20:11:41.977154
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '9ff29dda01d9'
down_revision: Union[str, Sequence[str], None] = '627b588b631b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='not_generated', nullable=False),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('why_it_matters', sa.Text(), nullable=True),
    sa.Column('impact_areas', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('known_facts', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('qualified_implications', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('uncertainties', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_interpretations')
    # ### end Alembic commands ###